spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buddy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

jwt:
  issuer: buddy # 실제 배포 이후 도메인으로 변경 예정
  secret: buddy-secret-ket # 실제 배포 이후 Base64로 인코딩된 문자열로 변경 예정